-- SUPERSEDED. The authoritative schema lives in supabase/migrations/.
--   * supabase/migrations/0001_init.sql   — tables + indexes
--   * supabase/migrations/0002_rls.sql    — RLS policies on every table
--   * supabase/test_auth_shim.sql         — auth.uid()/auth.users shim for local Postgres
--
-- Apply order: shim (local only) → 0001 → 0002. On Supabase, the shim is unnecessary
-- because auth.users + auth.uid() are provided by the platform.
